>general
#BEGIN_VARIABLES
PFAM_DIR hmm_dir/Pfam-A.hmm ripp_modules/borosin/hmms/*.hmm
int PRECURSOR_MIN 40
int PRECURSOR_MAX 1200
bool PRINT_PRECURSORS YES
bool EXHAUSTIVE YES
#END_VARIABLES

#BEGIN_COLORS
PF00590 #B3E5B4
NMT_1 #2D8630
NMT_2 #2D8630
BoroMT #2D8630
PF07746 #B3C6E5
BBD_A #0D47A1
BBD_B #0D47A1
BoroLegA #450838
BoroLegB #450838
Boro_6_8 #4a1822
#END_COLORS

>>